<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
  <compounddef id="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception" kind="class" language="Python" prot="public">
    <compoundname>armor_api::armor_exceptions::ArmorPyException</compoundname>
    <basecompoundref prot="public" virt="non-virtual">Exception</basecompoundref>
    <derivedcompoundref refid="classarmor__api_1_1armor__exceptions_1_1_armor_service_call_error" prot="public" virt="non-virtual">armor_api.armor_exceptions.ArmorServiceCallError</derivedcompoundref>
    <derivedcompoundref refid="classarmor__api_1_1armor__exceptions_1_1_armor_service_internal_error" prot="public" virt="non-virtual">armor_api.armor_exceptions.ArmorServiceInternalError</derivedcompoundref>
      <sectiondef kind="public-attrib">
      <memberdef kind="variable" id="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception_1a8d82ddb2fb30134207c9e180d614eba4" prot="public" static="no" mutable="no">
        <type></type>
        <definition>armor_api.armor_exceptions.ArmorPyException::msg</definition>
        <argsstring></argsstring>
        <name>msg</name>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="utilities/armor_api/armor_exceptions.py" line="18" column="1" bodyfile="utilities/armor_api/armor_exceptions.py" bodystart="18" bodyend="-1"/>
      </memberdef>
      </sectiondef>
      <sectiondef kind="public-func">
      <memberdef kind="function" id="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception_1ae8977bd8f05ae51646afa56a14c56cec" prot="public" static="no" const="no" explicit="no" inline="no" virt="non-virtual">
        <type>def</type>
        <definition>def armor_api.armor_exceptions.ArmorPyException.__init__</definition>
        <argsstring>(self, message)</argsstring>
        <name>__init__</name>
        <reimplementedby refid="classarmor__api_1_1armor__exceptions_1_1_armor_service_call_error_1a4b428d330758b5c3fe0ba395aa3560d9">__init__</reimplementedby>
        <param>
          <type>self</type>
          <defname>self</defname>
        </param>
        <param>
          <type>message</type>
          <defname>message</defname>
        </param>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="utilities/armor_api/armor_exceptions.py" line="17" column="1" bodyfile="utilities/armor_api/armor_exceptions.py" bodystart="17" bodyend="21"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>armor_api.armor_exceptions.ArmorPyException</label>
        <link refid="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>Exception</label>
      </node>
      <node id="4">
        <label>armor_api.armor_exceptions.ArmorServiceInternalError</label>
        <link refid="classarmor__api_1_1armor__exceptions_1_1_armor_service_internal_error"/>
        <childnode refid="1" relation="public-inheritance">
        </childnode>
      </node>
      <node id="3">
        <label>armor_api.armor_exceptions.ArmorServiceCallError</label>
        <link refid="classarmor__api_1_1armor__exceptions_1_1_armor_service_call_error"/>
        <childnode refid="1" relation="public-inheritance">
        </childnode>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>armor_api.armor_exceptions.ArmorPyException</label>
        <link refid="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>Exception</label>
      </node>
    </collaborationgraph>
    <location file="utilities/armor_api/armor_exceptions.py" line="16" column="1" bodyfile="utilities/armor_api/armor_exceptions.py" bodystart="16" bodyend="22"/>
    <listofallmembers>
      <member refid="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception_1ae8977bd8f05ae51646afa56a14c56cec" prot="public" virt="non-virtual"><scope>armor_api::armor_exceptions::ArmorPyException</scope><name>__init__</name></member>
      <member refid="classarmor__api_1_1armor__exceptions_1_1_armor_py_exception_1a8d82ddb2fb30134207c9e180d614eba4" prot="public" virt="non-virtual"><scope>armor_api::armor_exceptions::ArmorPyException</scope><name>msg</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
